G2NFA: G2NFA.cpp Gram_t.cpp NFA_t.cpp Estado_G_t.cpp produccion_t.cpp estado_t.cpp transicion_t.cpp
	g++ -Wall -g -std=c++11 G2NFA.cpp Gram_t.cpp NFA_t.cpp Estado_G_t.cpp produccion_t.cpp estado_t.cpp transicion_t.cpp -o G2NFA

clean:
	rm G2NFA